# API server
base.url=https://6a0b26d121e44562569776b2.mockapi.io/dev
address.firstLine=19 Great Margaret Road
address.postCode=SL5 9ZQ
customer.phone=071891111111
customer.firstName=Ram
customer.lastName=Rishi
#####################################
customer.detailChanged=first line
#####################################
customer.email=ram.rishi@test.com
customer.address.postCode=TW9 10XZ
customer.address.firstLine=500 Windsor Road
customer.status=ACTIVE
# PostgreSQL database
db.url=jdbc:postgresql://localhost:5432/banking
db.username=lkjoshi
db.password=$L2k8j72